repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check # Configure in .gitattributes
      - id: git-dirty # Configure in .gitattributes
      - id: markdownlint # Configure in .gitattributes
      - id: shellcheck
      - id: shfmt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        args: [--write, --config=.prettierrc]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--settings-file=pyproject.toml] # Configure in pyproject.toml
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black # Configure in pyproject.toml
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: ensure_venv.sh
        language: script
        types: [python]
        args: [pylint, -v, --rcfile=.pylintrc]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--config=pyproject.toml] # Configure in pyproject.toml
        additional_dependencies: [tomli]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, pyproject.toml] # Configure in pyproject.toml
        additional_dependencies: ['bandit[toml]']
