#!/bin/bash
rebuild_venv=0
if [ $# -gt 0 ] && { [ "$1" = "0" ] || [ "$1" = "1" ]; }; then
	rebuild_venv="$1"
	shift
fi

source setup_python_app.sh \
	--debug \
	--python_version="3.14.3" \
	--package_manager="poetry" \
	--rebuild_venv="$rebuild_venv" \
	--include_jumanji_house \
	--include_prettier \
	--include_isort \
	--isort_profile="black" \
	--python_formatter="black" \
	--pylint_enabled \
	--flake8_enabled \
	--mypy_enabled \
	--pytest_enabled \
	--pre_commit_autoupdate \
	--overwrite_vscode_launch \
	--line_length=120 \
	--pre_commit_pylint_entry_prefix="" \
	"$@"
