#!/bin/bash
rebuild_venv="$1"
rebuild_venv="${rebuild_venv:-0}"
source setup_python_app.sh \
	--debug \
	--package_manager="poetry" \
	--rebuild_venv="$rebuild_venv" \
	--isort_profile="black" \
	--python_formatter="black" \
	--overwrite_vscode_launch \
	--line_length=120 \
	--pre_commit_pylint_entry_prefix=""
