name: Python 3.8

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.8'
  POETRY_VERSION: '1.4.2'
  LINT_PATHS: >
    src
    tests
    setup_flake8.py
    setup_pre_commit_config.py
    setup_pylintrc.py
    setup_pyproject_toml.py
    setup_tox_ini.py
    setup_vscode.py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root --without dev
        if: steps.cache_dependencies.outputs.cache-hit != 'true'

      - name: Flake8
        run: poetry run flake8 ${{ env.LINT_PATHS }}

      - name: Pylint
        run: poetry run pylint ${{ env.LINT_PATHS }}

      - name: Pydocstyle
        run: poetry run pydocstyle ${{ env.LINT_PATHS }}

      - name: Bandit
        run: poetry run bandit -c pyproject.toml -r .

      - name: Pytest
        run: poetry run pytest -n auto
