name: Python 3.11

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.8.3"
  LINT_PATHS: >
    src
    tests
    setup_fix_prettier_pre_commit.py
    setup_flake8.py
    setup_pre_commit_config.py
    setup_prettierrc.py
    setup_pylintrc.py
    setup_pyproject_toml.py
    setup_vscode_settings.py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root --without dev

      - name: Flake8
        run: poetry run flake8 ${{ env.LINT_PATHS }}

      - name: Pylint
        run: poetry run pylint ${{ env.LINT_PATHS }}

      - name: Mypy
        run: poetry run mypy ${{ env.LINT_PATHS }}

      - name: Pytest
        run: poetry run pytest --cov -n auto
